^define: &img_shape [ 1024, 1024 ]

logger:
  project: Retinal Lesions Segmentation

model:

data:
  img_size: *img_shape
  batch_size: 32  
  valid_size: 0.15
  ^num_workers: 8
  ^eval_batch_size: 1
  use_cache: True
  ^persistent_workers: True
  crop_size: [512, 512]
  weightedSampler: False

trainer:
  accumulate_grad_batches: 1
  accelerator: gpu
  devices: auto
  max_epochs: 1250
  early_stopping: True
  precision: 32
  check_val_every_n_epoch: 25
  num_sanity_val_steps: 2
  log_every_n_steps: 50
  sync_batchnorm: True
